--1. What is the total revenue generated by male VS female customers?

SELECT 
gender,SUM(purchase_amount) as reveue
From dbo.customer_shopping_behavior
group by gender

--2.Which customers used a discount but still spent more than the average purchase amount?

SELECT
    customer_id,
    purchase_amount
FROM dbo.customer_shopping_behavior
WHERE purchase_amount > (SELECT AVG(purchase_amount)
       FROM dbo.customer_shopping_behavior)AND discount_applied = 'Yes';

--3.Which are the top 5 products with the highest average review rating?

SELECT TOP 5
item_purchased ,Avg(review_rating) AS "Average review rating"
From dbo.customer_shopping_behavior
group by item_purchased
order by AVG(review_rating) desc

--4 Compare the average purchase Amounts between Standard and Express Shipping

SELECT
shipping_type,
AVG(purchase_amount) AS"Average purchase amount"
FROM dbo.customer_shopping_behavior
Where shipping_type in ('Standard', 'Express')
group by shipping_type

--5 Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
Count(customer_id)AS "Count of Customers",
AVG(purchase_amount) AS average_spend,
Round(SUM(purchase_amount),2) as total_revenue,
subscription_status
FROM dbo.customer_shopping_behavior
group by subscription_status
order by total_revenue,average_spend desc

--6 Which 5 products have the highest percentage of purchases with discounts applied

SELECT TOP 5
item_purchased,
ROUND( 100* SUM(CASE When discount_applied = 'Yes' THEN 1 Else 0 END )/COUNT(*) ,2) as discount_rate
From dbo.customer_shopping_behavior
group by item_purchased
order by discount_rate desc

--7 Segment Customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id , previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS Customer_segment
From dbo.customer_shopping_behavior
)
SELECT
Customer_segment,
COUNT(*) as "Number of Customers"
FROM customer_type
group by Customer_segment
order by [Number of Customers] desc

--8. What are the top 3 most purchased products within each category
with item_counts as(
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count (customer_id)desc ) as item_rank
From dbo.customer_shopping_behavior
group by category , item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3

--9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Select 
subscription_status,
count (customer_id) as repeat_buyers
from dbo.customer_shopping_behavior
where previous_purchases > 5
group by subscription_status

--10. What is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount) as total_revenue
from dbo.customer_shopping_behavior
group by age_group
order by total_revenue desc